# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  otlp/1:
    endpoint: vsi-s390x-01:24317
    tls:
      insecure: true
  otlp/2:
    endpoint: vsi-s390x-01:34317
    tls:
      insecure: true
  loki:
    endpoint: http://vsi-s390x-01:3100/loki/api/v1/push
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]      
      exporters: [otlp/1]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/2]
    logs:
      receivers: [otlp]
      processors: [batch]      
      exporters: [loki]
