# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event.domain, event.name
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, service.namespace
exporters:
  otlp/1:
    endpoint: jaeger-service:24317
    tls:
      insecure: true
  otlp/2:
    endpoint: prometheus-service:34317
    tls:
      insecure: true
  loki:
    endpoint: http://loki-service:3100/loki/api/v1/push
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]      
      exporters: [otlp/1]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/2]
    logs:
      receivers: [otlp]
      processors: [batch, attributes, resource]      
      exporters: [loki]
