version: "3.7"
services:
  jaeger-service:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 14250:14250
      - 16686:16686
    networks:
      - nw-lab001
  prometheus-service:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus/config.yml/:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - 9090:9090
    networks:
      - nw-lab001
  grafana-service:
    image: ubuntu/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - nw-lab001
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=Editor
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  loki-service:
    image: ubuntu/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml    
    command: 
      -config.file=/etc/loki/config.yaml
    networks:
      - nw-lab001
networks:
  nw-lab001:
